### ISSUE TITLE
Unable to produce response

### ISSUE THREAD

**Issue by gabriellebtrc** [xlanor/SIM-UoW-Timetable-bot#71]
After sending commands, the bot stay still, doesn't send anything back.

**Comment by Poonjh95** [comment]
Bump! Same issue here. Can't get a response. Not updating timetable, I can't even stop it from sending me notifications for lessons I don't have :(

![Screenshot_20201001_041432_org telegram messenger](https://user-images.githubusercontent.com/72166431/94734997-a43a5580-039c-11eb-8502-c863f451aa6f.jpg)

**Comment by xlanor** [comment]
@Poonjh95 , @gabriellebtrc 

I've taken the bot down from my server due to a lack of time in maintainance. I'm looking for an active team of students to maintain the bot, because I no longer have a SIMConnect account.

Feel free to reach out to me on telegram and let's talk about this there. I can still assist with project coordination.

**Comment by Poonjh95** [comment]
DM me your telegram deets then!

Thanks

**Comment by gabriellebtrc** [comment]
Would like to be part of the project too! Send me your telegram username :)

**Comment by xlanor** [comment]
Drop me an email at contact@jingk.ai and let’s get a group going.

Jingkai.
